Mslq 82
StanfordMSL/msl_quad pull request #49
Opened 2020-10-05 06:17 UTC by haruki-msl

Ground Station page updated.

2020-10-19 21:41 UTC, exoticDFT requested changes
Content looks great and reads well! Just a couple of style guide related comments and one bigger question about the comments you have at the end.

2020-10-19 21:41 UTC, exoticDFT commented on docs/source/software/ground_station.rst
> +This section is for all things involving ground-based computers that are supporting the quad experiments. Apart from your own personal computer, you also need to have Optitrack (our motion capture sy
In the style guide we are trying to follow an 80 character limit to lines when possible. So nothing major, but if we can break this sentence into separate lines that are 80 characters or less, that would be awesome! For the URLs that run longer than 80 characters, there isn't anything I think we can, or should, do for that. Just having them on a separate line should be enough. Same thing applies to some of the paragraphs below.

2020-10-19 21:41 UTC, exoticDFT commented on docs/source/software/ground_station.rst
> +----------------------------------
Super minor, but ReStructuredText prefers to have a blank line after any header/title. So just adding one here and after the other headers should be good.

2020-10-19 21:41 UTC, exoticDFT commented on docs/source/software/ground_station.rst
> +.. For information regarding:
I think it's safe to remove these comments, unless we want to have some extra subsection here that tells the user they can get more information related to the ground station by look at these topics and adding links they can go to. @k2shah @lowjunen what do you guys think?

2020-10-26 14:25 UTC, haruki-msl commented on docs/source/software/ground_station.rst
> +This section is for all things involving ground-based computers that are supporting the quad experiments. Apart from your own personal computer, you also need to have Optitrack (our motion capture sy
Fixed in the new commit.

2020-10-26 14:25 UTC, haruki-msl commented on docs/source/software/ground_station.rst
> +----------------------------------
Fixed in the new commit.

2020-10-26 16:54 UTC, k2shah commented on docs/source/software/ground_station.rst
> +.. For information regarding:
I think a "related links" section would be enough

2020-10-26 16:54 UTC, k2shah approved these changes

2020-10-26 19:07 UTC, exoticDFT approved these changes
Everything looks great!

2020-10-26 19:07 UTC, exoticDFT commented on docs/source/software/ground_station.rst
> +.. For information regarding:
Looks great!

2020-10-26 21:13 UTC, haruki-msl commented on docs/source/software/ground_station.rst
> +.. For information regarding:
Will put the links in the external links section.

2020-11-02 16:38 UTC, haruki-msl commented
Ok, some comments in the ground station rst file have been moved to the external resources page, according to our previous discussion. I found the external resources page itself somewhat incomplete though. Could someone help edit it?

2020-11-02 21:08 UTC, exoticDFT requested changes
Changes look great and I think this is just about done. However, it seems that this branch was made before the recent correction to the external resources PR. So the conflicts that were made then are back again. We might need to merge the documentation branch into this before we actually finalize this PR.

2020-11-02 21:10 UTC, exoticDFT commented on docs/source/software/ground_station.rst
> +.. For information regarding:
Links moved to external resources look great. But I made a comment on the overall PR. I'm looking into this, but this conversation is good to resolve.

2020-11-02 21:10 UTC, k2shah commented
this is being merged into documentation? do you want to rebase it before merge?

2020-11-02 22:25 UTC, exoticDFT approved these changes

2020-11-02 22:27 UTC, merged