Quick start front
StanfordMSL/msl_quad pull request #52
Opened 2020-11-17 00:41 UTC by k2shah

moved the quick start guide and related assets to the top leave. Minor clean up elsewhere for consistency and added another video and ref

2020-11-18 22:00 UTC, exoticDFT requested changes
@k2shah The restructuring looks great! I really think this makes the documentation flow really well and very professional. Only one request.

The formatting of some of the files exceeds the character limit. I'm not concerned about the links that run too long, etc. But for the paragraphs, lists, etc. we should keep to the limit as much as possible.

2020-11-18 22:00 UTC, exoticDFT commented on docs/source/index.rst
> +Please review our :doc:`quickstart/index` to get starte.
started*

2020-11-21 03:09 UTC, k2shah commented on docs/source/index.rst
> +Please review our :doc:`quickstart/index` to get starte.
fixed

2020-11-21 03:09 UTC, k2shah commented
Ya i was going to set up ``black`` but in a different PR. i'll make a issue for setting up ``black``

2020-11-30 22:30 UTC, exoticDFT approved these changes
Looks great!

2020-12-01 00:07 UTC, rhaksar commented
Comments:
- on the "Ground Station" bullet point under "Setup", use an oxford comma: "mocap.local[,] and your own personal computer"
- on the "Companion Computer" bullet point, maybe clarify that this computer is typically on-board the vehicle?
- Use "ol'" or "old" instead of "ole" under the Safety Checklist
- does "4" need to be italic under "Mechanical"?
- under the "Safety Checklist" maybe use the same shorthand as the "Setup"? so "**FCU**" instead of "fcu" and "**CC**" instead of cc

2020-12-03 03:14 UTC, merged